### ISSUE TITLE
玩家可使用/back ID命令，强制他人返回上一个传送点

### ISSUE THREAD

**Issue by SHIJIATONG** [lRENyaaa/MinecraftRenYuanSurvivalServerPack#4]
使用默认普通玩家权限执行/back ID命令
![20230118003010](https://user-images.githubusercontent.com/96941909/212956573-713692b6-e9ff-47cd-a5c9-8c57cbef5c09.png)
可将其他玩家强制传送

**Comment by lRENyaaa** [comment]
应该是权限问题
鸽了,过几天修

**Comment by lRENyaaa** [comment]
已在 https://github.com/RenYuan-MC/RYSurvival/commit/aa8cf81d4091675c7405df30a49859112f537ab9 修复
