### ISSUE TITLE
能否替换服务器核心？（PSC生电）

### ISSUE THREAD

**Issue by 2869949486** [lRENyaaa/MinecraftRenYuanSurvivalServerPack#6]
能否直接替换？不做其他修改？

[1.19.3]PSC 服务端—— 让插件服同时支持生电吧！
https://www.mcbbs.net/thread-1421085-1-1.html
(出处: Minecraft(我的世界)中文论坛)

**Comment by lRENyaaa** [comment]
看了,理论上没问题,有问题的话开个新issues即可
